; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define AppName "Akko Hub"
#define AppId "E4CA0A60-4573-483B-8E56-884F19770908"
#define AppVerName "Akko Hub V1.4.0"
#define AppExe "AKKOStudio.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#AppId}
AppName={#AppName}
AppVerName={#AppVerName}
AppPublisher=深圳银宸电子科技有限公司
AppPublisherURL=http:///
AppSupportURL=http:///
AppUpdatesURL=http:///
DefaultDirName={commonappdata}\AkkoHub
DefaultGroupName={#AppName}
AllowNoIcons=yes
UsePreviousAppDir=yes
OutputDir=Z:\参考资料
OutputBaseFilename=AkkoHubInstaller-V5.06-Win20260512
SetupIconFile=Akko.ico
Compression=lzma
SolidCompression=yes
Uninstallable=yes
CreateUninstallRegKey=yes
UninstallDisplayName={#AppVerName}
UninstallDisplayIcon={app}\Akko.ico
PrivilegesRequired=admin

[Languages]
Name: "Enlish"; MessagesFile: "compiler:Default.isl"
Name: "Chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "Chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
Name: "Japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "Korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "French"; MessagesFile: "compiler:Languages\French.isl"
Name: "German"; MessagesFile: "compiler:Languages\German.isl"
Name: "Portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "Russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "Slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "Swedish"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "Turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "Thai"; MessagesFile: "compiler:Languages\Thai.isl"
Name: "Italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Files]
;Source: bin\*; DestDir: {app}; Flags: recursesubdirs ignoreversion
Source: bin\AKKOStudio.exe; DestDir: {app}; Flags: ignoreversion
Source: bin\AKKO.ico; DestDir: {app}; Flags: ignoreversion

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons};

[Icons]
Name: {group}\{#AppName}; Filename: {app}\{#AppExe}
Name: {group}\{cm:UninstallProgram,{#AppName}}; Filename: {uninstallexe}; IconFilename: {app}\Akko.ico
Name: {userdesktop}\{#AppName}; Filename: {app}\{#AppExe}; Tasks: desktopicon

[Run]
Filename: {app}\{#AppExe}; Description: {cm:LaunchProgram,{#AppName}}; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKLM; Subkey: Software\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: AkkoHub; ValueData: {app}\{#AppExe}; Flags: uninsdeletevalue;
;Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\{#AppId}"; Flags: uninsdeletekey

[Code]
var
  UninstallPath: String;
  ResultCode: Integer;

function RemoveOldVersion(): Boolean;
var
  UninstallString: String;
begin
  Result := True; 
  UninstallPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#AppId}_is1');

  if RegQueryStringValue(HKLM, UninstallPath, 'UninstallString', UninstallString) then
  begin
    if Exec(UninstallString, '/SILENT', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
    begin
    end
  end;
end;

// 入口函数：在初始化安装时调用
function InitializeSetup(): Boolean;
begin
  Result := True; 
  if not RemoveOldVersion() then
  begin
  end;
end;