; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define AppName "Akko Hub"
#define AppId "E4CA0A60-4573-483B-8E56-884F19770908"
#define AppVerName "Akko Hub V1.3.0"
#define AppExe "AKKOStudio.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#AppId}
AppName={#AppName}
AppVerName={#AppVerName}
AppPublisher=深圳银宸电子科技有限公司
AppPublisherURL=http:///
AppSupportURL=http:///
AppUpdatesURL=http:///
DefaultDirName={commonpf}\AkkoHub
DefaultGroupName={#AppName}
AllowNoIcons=yes
UsePreviousAppDir=yes
OutputDir=Z:\参考资料
OutputBaseFilename=AkkoHubInstaller-V5.06-Win20260512
SetupIconFile=Akko.ico
Compression=lzma
SolidCompression=yes
PrivilegesRequired=lowest
Uninstallable=yes
CreateUninstallRegKey=yes
UninstallDisplayName={#AppVerName}
UninstallDisplayIcon={app}\Akko.ico

[Languages]
Name: "Enlish"; MessagesFile: "compiler:Default.isl"
Name: "Chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "Chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
Name: "Japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "Korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "French"; MessagesFile: "compiler:Languages\French.isl"
Name: "German"; MessagesFile: "compiler:Languages\German.isl"
Name: "Portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "Russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "Slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "Swedish"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "Turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "Thai"; MessagesFile: "compiler:Languages\Thai.isl"
Name: "Italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Files]
Source: bin\*; DestDir: {app}; Flags: recursesubdirs ignoreversion
Source: bin\AKKOStudio.exe; DestDir: {app}; Flags: ignoreversion
Source: bin\AKKO.ico; DestDir: {app}; Flags: ignoreversion

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons};

[Icons]
Name: {group}\{#AppName}; Filename: {app}\{#AppExe}
Name: {group}\{cm:UninstallProgram,{#AppName}}; Filename: {uninstallexe}; IconFilename: {app}\Akko.ico
Name: {userdesktop}\{#AppName}; Filename: {app}\{#AppExe}; Tasks: desktopicon

[Run]
Filename: {app}\{#AppExe}; Description: {cm:LaunchProgram,{#AppName}}; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: Software\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: AkkoHub; ValueData: {app}\{#AppExe}; Flags: uninsdeletevalue;
Root: HKLM; Subkey: "Software\Microsoft\Windows\CurrentVersion\{#AppId}"; Flags: uninsdeletekey

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  ResultCode: Integer;
begin
  if CurStep = ssInstall then
  begin
    // 尝试静默结束进程
    // taskkill /F 表示强制结束，/IM 指定映像名称
    Exec(ExpandConstant('{sys}\taskkill.exe'), '/F /IM {#AppExe}', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    // ResultCode 为 0 表示成功，为 128 表示未找到进程，其他值表示失败
  end;
end;