; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
#define AppName "Akko Hub"
#define AppId "E4CA0A60-4573-483B-8E56-884F19770908"
#define AppVerName "Akko Hub V1.5.0"
#define AppExe "AKKOStudio.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={#AppId}
AppName={#AppName}
AppVerName={#AppVerName}
AppPublisher=深圳银宸电子科技有限公司
AppPublisherURL=http:///
AppSupportURL=http:///
AppUpdatesURL=http:///
DefaultDirName={commonappdata}\AkkoHub
DefaultGroupName={#AppName}
AllowNoIcons=yes
UsePreviousAppDir=yes
OutputDir=Z:\发布软件
OutputBaseFilename=AkkoHubInstaller-V5.14-Win20260525
SetupIconFile=Akko.ico
Compression=lzma
SolidCompression=yes
Uninstallable=yesmqtt
CreateUninstallRegKey=yes
UninstallDisplayName={#AppVerName}
UninstallDisplayIcon={app}\Akko.ico
PrivilegesRequired=admin
DisableDirPage=no
AlwaysShowDirOnReadyPage=yes

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Languages]
Name: "Enlish"; MessagesFile: "compiler:Default.isl"
Name: "Chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
Name: "Chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
Name: "Japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "Korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "French"; MessagesFile: "compiler:Languages\French.isl"
Name: "German"; MessagesFile: "compiler:Languages\German.isl"
Name: "Portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "Russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "Slovenian"; MessagesFile: "compiler:Languages\Slovenian.isl"
Name: "Swedish"; MessagesFile: "compiler:Languages\Swedish.isl"
Name: "Turkish"; MessagesFile: "compiler:Languages\Turkish.isl"
Name: "Thai"; MessagesFile: "compiler:Languages\Thai.isl"
Name: "Italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Files]
Source: bin\ByExe\*; DestDir: {app}\ByExe; Flags: recursesubdirs ignoreversion overwritereadonly
Source: bin\JmExe\*; DestDir: {app}\JmExe; Flags: recursesubdirs ignoreversion overwritereadonly
Source: bin\RyExe\*; DestDir: {app}\RyExe; Flags: recursesubdirs ignoreversion overwritereadonly
Source: bin\WsExe\*; DestDir: {app}\WsExe; Flags: recursesubdirs ignoreversion overwritereadonly
Source: bin\Main\*; DestDir: {app}; Flags: recursesubdirs ignoreversion overwritereadonly
Source: bin\Main\AKKOStudio.exe; DestDir: {app}; Flags: ignoreversion overwritereadonly
Source: bin\Main\AKKO.ico; DestDir: {app}; Flags: ignoreversion overwritereadonly

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons};

[Icons]
Name: {group}\{#AppName}; Filename: {app}\{#AppExe}
Name: {group}\{cm:UninstallProgram,{#AppName}}; Filename: {uninstallexe}; IconFilename: {app}\Akko.ico
Name: {userdesktop}\{#AppName}; Filename: {app}\{#AppExe}; Tasks: desktopicon

[Run]
Filename: {app}\{#AppExe}; Description: {cm:LaunchProgram,{#AppName}}; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: Software\Microsoft\Windows\CurrentVersion\Run; ValueType: string; ValueName: AkkoHub; ValueData: {app}\{#AppExe}; Flags: uninsdeletevalue;
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\{#AppId}_is1"; Flags: uninsdeletekey

[Code]
var
  UninstallPath: String;
  ResultCode: Integer;

function RemoveOldVersion(): Boolean;
var
  UninstallString: String;
begin
  Result := True; 
  UninstallPath := ExpandConstant('Software\Microsoft\Windows\CurrentVersion\Uninstall\{#AppId}_is1');

  if RegQueryStringValue(HKCU, UninstallPath, 'UninstallString', UninstallString) then
  begin
    Exec(UninstallString, '/SILENT', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
    Exec(UninstallString, '/SILENT', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

// 入口函数：在初始化安装时调用
function InitializeSetup(): Boolean;
begin
  Result := True; 
  RemoveOldVersion();
end;